changelog:
  categories:
    - title: Frontend
      labels:
        - frontend
      exclude:
        labels:
          - chore
    - title: Backend
      labels:
        - backend
      exclude:
        labels:
          - chore
    - title: Miscellaneous
      labels:
        - "*"
      exclude:
        labels:
          - frontend
          - backend
          - dependencies
    - title: Dependency Updates
      labels:
        - dependencies
      exclude:
        labels:
          - chore
