changelog:
  categories:
    - title: Frontend
      labels:
        - frontend
    - title: Backend
      labels:
        - backend
    - title: Miscellaneous
      labels:
        - "*"
    - title: Dependency Updates
      labels:
        - dependencies
