changelog:
  categories:
    - title: Frontend
      labels:
        - frontend
    - title: Backend
      labels:
        - backend
    - title: Dependency Updates
      labels:
        - dependencies
