services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          initial_sync: true
        - action: rebuild
          path: ./frontend/package-lock.json
    healthcheck:
      interval: 30s
      start_interval: 1s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=true
      - ALLOWED_HOSTS=backend,localhost
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
    healthcheck:
      interval: 30s
      start_interval: 1s
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          initial_sync: true
        - action: rebuild
          path: ./backend/uv.lock

  database:
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      interval: 30s
      start_interval: 1s

  # pgui:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     database:
  #       condition: service_healthy
  
  # chartdb:
  #   image: ghcr.io/chartdb/chartdb:latest
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - DISABLE_ANALYTICS=true

volumes:
  postgres_data:
