services:
  tunnel:
    image: cloudflare/cloudflared:latest
    depends_on:
      frontend:
        condition: service_healthy
    command: tunnel run
    environment:
      - TUNNEL_TOKEN_FILE=/run/secrets/dumbjared_cloudflared_token
      - TUNNEL_METRICS=localhost:60123   
      - NO_AUTOUPDATE=true
    secrets:
      - dumbjared_cloudflared_token
    networks:
      - ingress
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "--metrics", "localhost:60123", "ready"]
      interval: 20s
      timeout: 5s
      start_period: 30s
      start_interval: 3s

  frontend:
    image: neutronlul/dumbjared-frontend:latest
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - internal
      - ingress
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:3000"]
      interval: 20s
      timeout: 5s
      start_period: 30s
      start_interval: 5s

  backend:
    image: neutronlul/dumbjared-backend:latest
    environment:
      - SECRET_KEY_FILE=/run/secrets/dumbjared_backend_key
      - POSTGRES_PASSWORD_FILE=/run/secrets/dumbjared_postgres_password
      - TZ=America/Los_Angeles
    secrets:
      - dumbjared_backend_key
      - dumbjared_postgres_password
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal
    healthcheck:
      test: ["CMD", "python", "manage.py", "health_check"]
      interval: 20s
      timeout: 5s
      start_period: 30s
      start_interval: 5s

  database:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/dumbjared_postgres_password
    secrets:
      - dumbjared_postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 20s
      timeout: 5s
      start_period: 1m
      start_interval: 5s

volumes:
  postgres_data:

networks:
  internal:
    driver: overlay
  ingress:
    driver: overlay

secrets:
  dumbjared_cloudflared_token:
    external: true
  dumbjared_backend_key:
    external: true
  dumbjared_postgres_password:
    external: true