services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     backend:
  #       condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=true
      - ALLOWED_HOSTS=backend,localhost
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Los_Angeles
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "manage.py", "health_check"]
      interval: 30s
      timeout: 5s
      start_period: 1m
      start_interval: 1s
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          initial_sync: true
        - action: rebuild
          path: ./backend/uv.lock
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 5s
      start_period: 1m
      start_interval: 1s

  # pgui:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     database:
  #       condition: service_healthy
  
  # chartdb:
  #   image: ghcr.io/chartdb/chartdb:latest
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - DISABLE_ANALYTICS=true

volumes:
  postgres_data: