version: "3.9"

services:
  postgresql_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: scraper_user
      POSTGRES_PASSWORD: scraper_pass
      POSTGRES_DB: scraper_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
